### ISSUE TITLE
Auto update app itself

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#1]
We want to have functionality so our Electron app auto updates itself.

## Acceptance criteria

* [x] auto update the app on start

## Tasks

* [x] analysis
* [x] refactor index.js
* [x] test out using test releases

## Analysis

For MacOS:
* Use auto-updater suggested by electron.build - https://www.electron.build/auto-update
* refactor index.js
* follow guide here - https://github.com/iffy/electron-updater-example

**Comment by anuveyatsu** [comment]
FIXED

**Comment by anuveyatsu** [comment]
Not functioning at the moment. Need to investigate

**Comment by anuveyatsu** [comment]
FIXED and working from version `0.1.11`
