### ISSUE TITLE
Track events in the app

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#10]
How we can track events in the app (e.g. installs, errors, crashes etc)? stuff like https://electronjs.org/docs/api/crash-reporter 

and using sentry may be useful https://docs.sentry.io/clients/javascript/integrations/electron/

## Acceptance criteria

* [x] all unhandled rejections are tracked in Sentry

## Tasks

* [x] create an account on Sentry.io
* [x] setup error reporting for main process
* [x] setup error reporting for renderer process

**Comment by anuveyatsu** [comment]
FIXED and available in v0.4.2 - https://github.com/datahq/data-desktop/releases/tag/v0.4.2
