### ISSUE TITLE
Progress indicator/notifications on push

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#11]
*As the data desktop app user I want to have a sense of how publishing of my dataset is going so I am sure it is working and I know what is happening (e.g., authenticating, uploading etc.).*

Once a user clicks "Publish" button, we want to start showing some indicators so the user knows that push started and working. E.g., on top of the page, we remove input element, change message saying that it is publishing to some URL and change button text saying "In progress" + have a spinner. Also, we can have notifications: one when push starts and second when finishes. Clicking on the second notification should open online showcase page in the default browser.

## Acceptance criteria

* [x] Once I click on publish button, I am sure push is started
* [x] Once my dataset is online I get a notification and I can visit the page easily with 1 click

## Tasks

* [x] refactor `pages` to change messages and have a spinner
* [x] refactor `utils/push.js` to show notifications

**Comment by anuveyatsu** [comment]
Decided to don't have a proper progress bar here as it is depended on the upstream library (datahub-client). Having progress bar on upload to aws is being tricky and requires broader analysis. This is an existing issue in the cli - https://github.com/datahq/datahub-cli/issues/116

Looking at now-desktop implementation, we can see that there is no progress bar on deploy and it doesn't seem essential. For now, it should be sufficient to have a spinner + notifications on start and finish of push process.

**Comment by anuveyatsu** [comment]
FIXED, available in https://github.com/datahq/data-desktop/releases/tag/v0.3.3
