### ISSUE TITLE
Edit URL for publishing a dataset

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#12]
On showcase window, beneath of publishing button, we want to have something like:

```
"/anu/rad-xyz-abc" - edit this if you want to publish to a different name or replace an existing dataset
```

Note that only dataset name can be edited and it would change `name` property in the descriptor (?)

## Acceptance criteria

* [x] I can edit URL prior publishing a dataset

## Tasks

* [x] refactor pages to have input element where users can edit dataset's name
* [x] refactor page scripts to handle user typed dataset name and pass to main process
* [x] refactor index.js to handle passed newName property and pass through to push.js
* [x] refactor push.js to use new name if provided
* [x] have a info message under the input element saying that this name can be edited so users do not need to guess

**Comment by anuveyatsu** [comment]
FIXED, available in https://github.com/datahq/data-desktop/releases/tag/v0.3.2
