### ISSUE TITLE
Validate datapackage.json and show error message if it is invalid

### ISSUE THREAD

**Issue by Mikanebu** [datahq/data-desktop#13]
When there is invalid JSON, it does nothing. Maybe be a good idea to validate or show an error message saying `SyntaxError: Unexpected token f in JSON at position 12`.

## Acceptance criteria

* [x] when I drop invalid JSON, it should show error message instead of doing nothing
* [x] when I drop `datapackage.json` which is invalid, it should tell me about the error

## Tasks

* [x] wrap with try catch code that reads the file and show errors using `showError` method
* [x] do validation of descriptor in showcase module and show errors using `showError` method

**Comment by anuveyatsu** [comment]
FIXED and available in v0.4.2 - https://github.com/datahq/data-desktop/releases/tag/v0.4.2
