### ISSUE TITLE
Ability to set a title for a dataset

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#14]
Usually when people change a name for their dataset, they would also want to change/set a title for it. Atm, we don't support changing title but it can be implemented quickly as we have worked out logic when implementing it for setting name.

## Acceptance criteria

* [x] I can set/change a title for my dataset prior pushing

## Tasks

* [x] refactor pages/showcase.ejs to make title an input element so users can edit it
* [x] refactor pages/script.ejs to handle changes in title and to pass to main process once a push is requested
* [x] have info message under the title saying that it is editable
* [x] refactor main/index.js to handle new property called newTitle and pass through to push.js
* [x] refactor utils/push.js to handle newTitle and change title if provided

**Comment by anuveyatsu** [comment]
FIXED, available in https://github.com/datahq/data-desktop/releases/tag/v0.3.4
