### ISSUE TITLE
Tableschema editor + validation info

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#15]
*As a Publisher I want to be able to edit a tableschema for my data so I can review it and correct/change if I need so.*

*As a Publisher I want to see if my tableschema is valid against my data so I can fix it and I know what exactly to fix.*

We want to refactor our "Field Information" table so it becomes editable (type and description columns only):
* do we need "Order" columns? I think it is useless
* I think we should separate columns for "format" and "type". E.g., sometimes we have `type=date` but format is incorrect `format=default` but I want to have some custom pattern for my date.

We also want to have a new column for validation info, where we can print validation errors or confirm it is valid.

To give users understanding of that the table is editable, we want to have "Edit" button next to table's title so clicking it would enable edit mode.

## Acceptance criteria

* [x] when I arrive at showcase page, I can see validity of my data against given table schema
* [x] I can edit table schema (type, format and description properties)
* [x] once I change something in table schema, I can see updated validity
* [x] once I am happy with my table schema, I can push my dataset with the edited table schema

## Tasks

* [x] Part 1 - refactor table's layout [30m]
  * [x] modify table according to analysis
* [x] Part 2 - implement validation (not editable yet) [3h]
  * [x] take schema and data source from given descriptor and call validate function
  * [x] print out result either valid or error message
  * [x] do this for each resource
* [x] Part 3 - implement editor [2h]
  * [x] button next to table's title which should have two states: edit and commit
  * [x] implement editor mode - may be simple input elements with disabled mode
* [x] Part 4 - implement validation on updated table schema [2h]
  * [x] using changed values of schema do validation and print results

## Analysis

New "Field Information" table would look like following:

**Field Information** [Edit/Commit]

| Field Name | Type    | Format | Description | Validity   |
|------------|---------|--------|-------------|------------|
| Date       | date    | any    | YYYY-MM-DD  | Valid      |
| Average    | number  |        |             | Valid      |
| Sum        | integer |        |             | Error: Wrong type for header: Value and value: 2647027405.99137 |

Do we want to validate again once user changed something? Then we need to do in browser validation:

```javascript=
const {Table} = require("tableschema")

function validate(resource) {
  Table.load(resource.path, {schema: resource.schema})
    .then(async table => {
        try {
          await table.read()
        } catch (err) {
          console.log(err[0].message) // display this message in the table
        }
    }) 
}

```

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/data-desktop/releases/tag/v0.4.0

Here is the example of pushing a dataset after fixing table schema - https://datahub.io/anuveyatsu/fixed-pop
