### ISSUE TITLE
Implement analytics tracker

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#16]
We want to track things like:

## Acceptance criteria

* [x] we are tracking:
  * [ ] installations (this is unknown if possible with ga)
  * [x] first runs of the app
  * [x] how many times users drop files into the tray
  * [x] how often pushs using the app
    * [x] successful pushs
  * [x] login requests (which might be counted as sign up)
  * [x] app updates (tracked once update is downloaded)
  * [x] how often data is validated against tableschema (note that it is auto validated when generating showcase page)

## Tasks

* [x] create a new GA id for Electron app so it is separate from the website
* [x] set it up in the main process
* [x] track needed events

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/data-desktop/releases/tag/v0.4.3
We are tracking "first runs" of the app but not tracking installations atm. See issue description for details what else we're tracking in the app.
