### ISSUE TITLE
Add options on push: public, hidden or private

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#17]
At the moment, when pushing data from the desktop app, users cannot change "findability" option and it is always "public". We want to give users options to change it so they can push as public, hidden or private

## Acceptance criteria

* [x] When I am pushing a data, I can select "findability" option for it

## Tasks

* [x] mockup and implement UI/UX
* [x] send "findability" along with dataset to be pushed over "publish-request" channel
* [x] set "findability" in the push.js module

**Comment by anuveyatsu** [comment]
FIXED and available in https://github.com/datahq/data-desktop/releases/tag/v0.4.4

![capturfiles 06 26 2017_20 26 37 png 2224x1624](https://user-images.githubusercontent.com/17809581/33699071-068d6318-db3b-11e7-940c-069cec86a570.png)
