### ISSUE TITLE
After publishing a dataset user should be logged in on the website (by coming from the app)

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#18]
*As a Publisher I want to be logged in when I visit the online showcase page so I always can see my own datasets on the website even if it is private.*

## Acceptance criteria

* [x] Once my dataset is published, I can visit the showcase page by clicking the provided links and I will be logged in on the website

## Tasks

* [x] refactor URLs to have "jwt" as params
  * [x] when returning a url from push.js module include "jwt" as params
  * [x] when sending info to notify.js module include "jwt" in the URL
* [x] refactor frontend to check for "jwt" in params (route for showcase page)

**Comment by anuveyatsu** [comment]
FIXED and available in https://github.com/datahq/data-desktop/releases/tag/v0.4.4
