### ISSUE TITLE
Research windows / linux versions of the app

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#19]
At the moment, we only have Macos version of the app but as we know there are plenty of website visitors that use other OS mostly Windows and Linux. We want to do a research about what it'd take us to release the versions for those OS.

## Acceptance criteria

* [ ] Estimate of what it'd take to release Windows and Linux versions of the app

## Tasks

* [ ] Read through docs on electron.build
* [ ] Try it out
