### ISSUE TITLE
No progress bar for installation (how much is it downloading, how long will it take)

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#2]
Atm, when users open the app, it shows "Installation window" with a spinner and message saying it is installing/updating CLI tool. If there is nothing to update or install it will then show a "done" window. However, if it needs to download the binary it may take time as the file's size is more than 100MB and increasing. For people with a slower connection, this process can take several minutes so they might think that app is just not responding/working.

To improve such user experience, we want to have a progress bar when downloading the file.

## Acceptance criteria

* [x] when using the app, i have clear indication of how long i need to wait until binaries are donwloaded

## Tasks

* [x] Tell the user that it is checking remote updates
* [x] Update the user whether updates found or not
* [x] Update the user about download start
* [x] Show a progress bar with how much downloaded and left

**Comment by anuveyatsu** [comment]
FIXED, will be included in the next release 0.2.0
