### ISSUE TITLE
Use DataHub logo in SVG

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#20]
*As a User of the desktop app I want all pages to load as quick as possible so I have smooth and nice UX while using the app.*

## Acceptance criteria

* [ ] we're using SVG version of datahub logo

## Tasks

* [ ] get the logo (from graphic designer?)
* [ ] replace it here
