### ISSUE TITLE
Feedback option in the app

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#21]
*As the DataHub team we want to give users to leave a feedback for us so we know their opinion about their experience and we can get any suggestions from them.*

## Acceptance criteria

* [ ] a message and a link to feedback on the main page

## Tasks

* [ ] add a message about leaving us a feedback just like in the website with a link to google forms (do it on the main page)
* [ ] make sure we're tracking it with GA

**Comment by rufuspollock** [comment]
I actually think this is quite secondary so dropping this to backlog for now.
