### ISSUE TITLE
App silently quits when I drop some invalid data file

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#25]
This is happening because Sentry is identifying "TableSchemaError" as a fatal and non-recoverable error. We can use a callback to handle it. Also, we don't want to send Table Schema errors to Sentry.

## Acceptance criteria

* [x] app does not quit when I drop invalid data file

## Tasks

* [x] research and debugging
* [x] add callback function to `.install()` method
* [x] don't send TableSchemaError to Sentry

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/data-desktop/releases/tag/v0.4.3
