### ISSUE TITLE
TableSchema editor: make "format" a drop-down

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#26]
As a Publisher, when editing table schema I want to have a drop-down for "format" value so:
* I can select available options
* I don't mistype values
* I know what's available

## Acceptance criteria

* [ ] when I edit table schema I have a drop-down with available options (depending on "type" property)

## Tasks

* [ ] refactor `showcase.js` module to pass a dictionary with available "type" values and appropriate "format" values for each of them
* [ ] refactor pages to have drop-downs
