### ISSUE TITLE
File icon is electron's default but we want the datahub logo

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#3]
If I download the app, the file icon would be the default electron's one:

<img width="176" alt="screen shot 2017-11-08 at 12 35 56" src="https://user-images.githubusercontent.com/17809581/32534799-66550b82-c481-11e7-9760-5aedfcd62005.png">

but we want to use our logo instead - http://datahub.io/static/img/logo-cube.png

## Acceptance criteria

* [x] the app has DataHub logo as file icon

## Tasks

* [x] set it up in package.json
* [x] rebuild the app
* [x] create a release and test
