### ISSUE TITLE
Implement tray with navigation/menu

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#5]
When opening the app, we want a tray to appear and stay there. This tray should be the black square logo:

* Initially, it should show checking updates status/behavoir under the tray in the small window.
* Clicking on the tray should show/hide the status window.
* The status window should have a current version information.
* The status window should have a link to the tutorial.

## Acceptance criteria

* [x] Points above are satisfied

## Tasks

* [x] analysis
* [x] implement tray
  * [x] make a logo for tray (16x16 and 32x32 px)
  * [x] initialize from index.js
* [x] refactor current windows
  * [x] create main window (which is also status)
  * [x] create tutorial window
* [x] bind tray with windows

**Comment by anuveyatsu** [comment]
FIXED - will be available with the latest release
