### ISSUE TITLE
Showcase on drag and drop (prior pushing)

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#6]
*As a desktop app user I want to see my data's showcase prior publishing online so I can fix any problems and I am in full control of what's going to be live.*

Something like "local showcase" which is simplified version of the showcase on the website. On this page, we should report about any issues in data, e.g., validation errors. This page also can have a graph if there are a view + preview tables using original resources. This "local showcase" would use original datapackage.json so some attributes generated by assembler would be skipped:

* Title - YES
* Summary table - YES but no size, formats and created/modified dates
* Short readme - YES
* Graph - YES
* Data Files table - NO as we don't have derived versions (but we can have a placeholder if necessary)
* Preview table - YES
* Field information table - YES
* Readme - YES
* Instructions - NO

## Acceptance criteria

* [x] when I drag and drop a single file it shows me showcase page for this file
* [x] when I drag and drop a "datapackage.json" file it shows me showcase page generated from it

## Tasks

* [x] set up a templating language
* [x] copy over showcase page's template from frontend lib
* [x] copy over bundle.js for rendering graphs and tables
* [x] refactor index.js to handle "on drop" events on tray
* [x] create showcase.js module to manage dropped files and generate showcase page
  * [x] if dropped file is datapackage.json, it should generate showcase page from it
  * [x] if dropped file is data file, it should generate datapackage for it and then generate showcase page (similar to cli approach `prepareDatasetFromFile` funciton)

**Comment by anuveyatsu** [comment]
FIXED and released here - https://github.com/datahq/data-desktop/releases/tag/v0.2.0

At the moment, preview tables and graphs are not working due to following issues and they will be fixed in the appropriate repos. Once it is fixed, we will update submodule here, after which views should work:

https://github.com/datahq/frontend-showcase-js/issues/171
https://github.com/frictionlessdata/tableschema-js/issues/110

**Comment by anuveyatsu** [comment]
FIXED and fully working from v0.2.2 - https://github.com/datahq/data-desktop/releases/tag/v0.2.2
