### ISSUE TITLE
Implement Login

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#7]
*As the Datopian we want to have smooth login process so users have a great experience while getting authenticated.*

We can have a message saying that users can login using GitHub account and a button just like in our website. Clicking the button would lead to same process as in the CLI's login.

## Acceptance criteria

* [x] login when clicking button similar to cli login process

## Tasks

* [x] refactor `index.js` to listen login requests on some "login-request" channel
* [x] implement login page similar to login page in the website
  * [x] pressing login button should behave like login process in CLI
* [x] refactor `showcase` page to have a button "login" that redirects to login page
* [x] implement `login.js` module in utils
  * [x] install datahub lib (once cli is splitted out) and reuse its functionality (just like in cli): config and login modules

**Comment by anuveyatsu** [comment]
FIXED - this won't have its own release as it'll be released together once "publish" functionality is implemented.
