### ISSUE TITLE
Implement push (publish) a dataset

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#8]
*As a desktop app user I want to be able to publish my data in a super easy and intuitive way so I don't need to spend time learning/debugging.*

This includes two steps:

1. First user needs to get some data, e.g., on the desktop into "local datasets" list. To do so he/she just need to drag and drop the data file into the Electron app's tray on the top. Once it is done, it would auto display "local showcase" page so user can check if there is any problems etc.
2. Second step is actually pushing/publishing. This should be done with one click. We can have a full width button fixed on the top of the page so it is easy to find and click:

Publish to: `/anu/rad-xyz-abc` [GO! <- this is the big button ]

rad-xyz-abc (beneath: "edit this if you want to publish to a different name or replace an existing dataset")

## Acceptance criteria

* [x] i have a button "publish" on showcase page to get the dataset online

## Tasks

* [x] refactor showcase page to have "publish" button fixed on top
* [x] create `push.js` module to prepare a dataset and calling DataHub api (once cli lib is splitted out)
  * [x] pass datapackage.json location to push.js
  * [x] generate Dataset object using `data.js` lib

![](https://i.imgur.com/vqnDIXI.png)

**Comment by zelima** [comment]
@anuveyatsu could you please move steps and images down into analysis section so that "acceptance criteria" and tasks comes right after user story

[DONE]

**Comment by anuveyatsu** [comment]
FIXED - available from v0.3.1 - https://github.com/datahq/data-desktop/releases/tag/v0.3.1
