### ISSUE TITLE
Research and analysis re Electron apps testing

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/data-desktop#9]
*As a developer of Electron app I want the app to be under automated tests so I am able to develop and maintain app in an efficient way.*

Here are some popular frameworks for testing Electron apps:

* https://github.com/electron/spectron
  * tutorial on how to do end-to-end testing - https://www.wintellect.com/end-end-testing-electron-apps-spectron/
* https://github.com/jprichardson/electron-mocha

## Acceptance criteria

* [ ] we have selected Electron app testing framework
* [ ] we have a sample test

## Tasks

* [ ] research and analysis
* [ ] come up with a framework and example of how to use it (sample test)
